### ISSUE TITLE
Not using DataObject::duplicate() when creating translations

### ISSUE THREAD

**Issue by tomspeak** [silverstripe/silverstripe-translatable#131]
Is there a reason that this line https://github.com/silverstripe/silverstripe-translatable/blob/master/code/model/Translatable.php#L1394

Doesn't just use `$this->owner->duplicate()` as it would then handle relationship duplication as well as the data duplication.

At the moment all has_ones remain assigned (which is often not desirable) and other relationships are not handled.

**Comment by NightJar** [comment]
Hi @tomspeak - thanks for taking the effort to report. Would you mind following up with a brief explanation as to why you've closed this? Even if it was a momentary confusion, perhaps there's some alteration we could make to documentation (or that comment you've linked) to make this clearer?
Perhaps we can help people in the future avoid the same experience you have had here.

**Comment by dhensby** [comment]
@NightJar I think because it's 5 years only and @tomspeak doesn't use SS any more :)

Plus it didn't have any response at all nor any other users that seemed to have this problem... On top of that, this module is being deprecated in favour of fluent, I believe, so seems fairly reasonable to close this ;)

**Comment by NightJar** [comment]
hahaha, so it is (old). Well, jolly good then :)
Onwards and upwards :D
