### ISSUE TITLE
Stop adding the locale to every URLSegment

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-translatable#183]
Example: you've got a page called `/team/john` and you want to translate it from English to French. The parent page 'team' has already been translated and is on `/equipe`. 

When you create the translation for the 'john' page, it will be put by default on `/equipe/john-fr-fr`. 

I argue that's a bad default. I have to go in every single time to remove that locale, because there's no use for it! It's a good idea when the original and the translation have the same parent, but other than that, it's just clutter in the URLSegment. 

I found `Config::inst()->update('Translatable', 'enforce_global_unique_urls', false);` and thought that might fix it, but then it will -never- add the locale again, translating `/team` to `/team`. So that's not a great solution. 

I believe that by default, urls should indeed be enforced to be unique, but it should only get the locale appended if a collision is indeed detected. Collisions usually only happen if the page is at the top level.

The required change concerns this code block (it need `&& willCollide` :-) ): 
https://github.com/silverstripe/silverstripe-translatable/blob/master/code/model/Translatable.php#L1458

**Comment by dhensby** [comment]
> I believe that by default, urls should indeed be enforced to be unique, but it should only get the locale appended if a collision is indeed detected. Collisions usually only happen if the page is at the top level.

Well, `/team/john` and `/lequipe/john` are collision `URLSegment`s as the pages themselves have the same `URLSegment`. It's about enforcing uniqueness globally not just in the context of it's current placement in the sitetree.

If you were to go to `/john` it would forward to `/team/john` and if you went  to `/john-fr-fr` it would forward to `/lequipe/john-fr-fr`

You're assuming that there is no collision if the parents are different, but this check is based on page-per-page comparison, not full URL comparison.

I see the argument both ways and that it could be irritating if you don't want URLs to have the language appended if they are nested in an already unique part of the site, but that is a specific approach that needs a config option as opposed to changing the current behaviours.

**Comment by JorisDebonnet** [comment]
I see, it would indeed need to be a config then. I personally never use the automated forward from `/URLSegment` to `/parent/URLSegment` (to be honest I don't really see the point of it), so I didn't think of that. For me, the config is better understandable as "enforce global unique urlsegments" :)

I guess that if a config were to be added, we'd need a somewhat verbose way of setting it 'the way I want' since global uniqueness needs to be turned off and then local turned on. 

Perhaps something like this?
```
Config::inst()->update('Translatable', 'enforce_global_unique_urls', false);
Config::inst()->update('Translatable', 'enforce_local_unique_urls', true);
```

As long as that first config is true, the second one is actually meaningless. But I feel it would be strange to have a new config that 'overwrites' the first - althought that *would* make it easier to set. Perhaps with a better config name...

**Comment by chillu** [comment]
> If you were to go to /john it would forward to /team/john and if you went to /john-fr-fr it would forward to /lequipe/john-fr-fr

That's not correct, check `ModelAsController` which adds a `ParentID = 0` check. Such a redirection would only work if the page previously existed on the root and has been moved since (through `OldPageRedirector`).

> You're assuming that there is no collision if the parents are different, but this check is based on page-per-page comparison, not full URL comparison.

Also not correct, check `ContentController::handleRequest()`.

`SiteTree:: validURLSegment()` should already take care of creating a unique segment for the current section (filters by ParentID), presumably because its queries automatically filter by locale. @JorisDebonnet I've just played around with `enforce_global_unique_urls: false`, and it seems to work as expected. I think this flag might have been made obsolete by a smarter routing logic in `Translatable`?

**Comment by JorisDebonnet** [comment]
Well, in `Translatable.php`'s [`createTranslation`](https://github.com/silverstripe/silverstripe-translatable/blob/master/code/model/Translatable.php#L1458) function, the value of `enforce_global_unique_urls` is used to decide whether the locale needs to be appended to the new page's default URLSegment. This is the only place where this config value is used. 

So if I leave `enforce_global_unique_urls` on its default value of `true`, a French translation for `/team/john` defaults to `/equipe/john-fr-fr`. When I turned it off, it will default to `/equipe/john`. But when turned off, if I would create a new translation for `/team`, it will also default that translated URLSegment to `/team`, effectively saving it on the "same URL". 

I guess, if as you say `SiteTree::validURLSegment()` should prevent that, that prevention is being overriden somewhere, although I can't find that happening in the code. It just calls [`write()`](https://github.com/silverstripe/silverstripe-translatable/blob/master/code/model/Translatable.php#L1465) a few lines after that check about suffixing the URLSegment. 

So anyway, I have some doubts about the way that currently works. `enforce_global_unique_urls==true` spawns unnecessary suffixes for subpages, but `enforce_global_unique_urls==false` creates colliding translations on the site's root-level.

**Comment by dhensby** [comment]
> That's not correct, check ModelAsController which adds a ParentID = 0 check. Such a redirection would only work if the page previously existed on the root and has been moved since (through OldPageRedirector).

I've just tested in a fresh install 3.1.10 and added a page under /home/never-made-before and then navigated to /never-made-before and it forwarded me automatically...

If the behaviour should not be what it currently is then there is a bug.

Otherwise it looks like the behaviour needs tweaking for translatable so it's less absolutist

**Comment by chillu** [comment]
@dhensby I stand corrected! Should've looked at the actual behaviour rather than just reasoning about the code details. That's really weird default behaviour, and I think more of an oversight when transitioning the codebase into "nested URLs" around the 2.3 release. 

On that note, there's some interesting discussion around the RedirectorPage default behaviour on https://github.com/silverstripe/silverstripe-cms/pull/1198.

@JorisDebonnet said:

> enforce_global_unique_urls==false creates colliding translations on the site's root-level.

The idea with that flag was to allow custom routing. For example, you could create controller prefixes for `mydomain.com/en/team` and `mydomain.com/fr/team`. But since this is custom routing, we can't make it the default. Your issue is slightly different from that I think. I would suggest you implement a `enforce_local_unique_urls` flag which limits uniqueness to the current language and the current parent context, so basically emulates `SiteTree->onBeforeWrite()`. Actually, that `SiteTree` behaviour should already kick in, it just has a `Locale` filter applied via `Translatable->augmentSQL()`. It might be easiest to replicate it in `Translatable->onBeforeWrite()`, because its going to be hard to catch that specific SQL query in `augmentSQL()` and avoid adding `Locale` there. Do you want to give it a try?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
