### ISSUE TITLE
Wrong locale field value on DataObject

### ISSUE THREAD

**Issue by suntrop** [silverstripe/silverstripe-translatable#190]
I've got a custom SiteConfig extension. The hidden field 'Locale' ist always the default locale, not the current locale.

<input type="hidden" name="Locale" value="de_DE" class="hidden" id="Form_ItemEditForm_Locale">

Why isn't the value updated to the current locale? Can't save new items to other locales.

**Comment by silverstripe-issues** [comment]
Code sample please

**Comment by Taitava** [comment]
I think I have something like this too. My case involves also the SilverStripe Blog module. The Blog module also uses silverstripe/lumberjack module to better manage the site tree of blog articles in the CMS. This module comes by default with the blog module, so it's not something I have included myself. Thus, I don't know if the Lumberjack module relates to this bug at all, but I just mentioned it just in case, because I don't know it very well.

So, what's the problem in practise? I have a site with two languages, English and Finnish, and English is the default language. I have one Blog page that is translated to both English and Finnish - that works well. While having English selected as the content language (in the dropdown field left above the site tree in the editor), if I create a new BlogPost under the Blog page, saving and publishing it goes well. But, if I want to write a blog article in Finnish, I switch the language from the dropdown field to Finnish and then create a new BlogPost page under the Blog page. I write the article and publish it. It saves the article with a wrong locale field value, 'en_US' instead of 'fi_FI'. I checked that directly from the database.

More strange, my new Finnish blog article won't appear in the CMS at all - no matter what language I select. It just doesn't show up in the gridfield that lists the blog articles. However, it does appear in the public site - but of course under the English side of it. Too bad for people who can't speak Finnish! :D

I have SilverStripe 3.1.12. Blog and Translatable are the newest versions - I have ran composer update today and don't have any version limits in composer.json for those two modules. Do you need any code samples? I think I don't have made any custom code relating to Translatable or Blog.

**Comment by Taitava** [comment]
Here is a temporary fix in a form of an extension, so no need to hack any existing files:

mysite/code/BlogPostLanguageFix.php:
```
<?php
/**
 * For some reason the value of the Locale field of BlogPost objects do not reflect the locale that is currently
 * selected in the CMS, but instead always the default locale. This is a quick and dirty way to fix it. This extension
 * checks every time a BlogPost objects gets saved that its Locale field has the same value as what is currently
 * selected in the CMS editor, and if not, fixes the value.
 * The use of this extension is not recommended for a long term solution (because it does not address the original bug),
 * but it is instead a quick fix to put down the fire. I recommend you to remove this after someone fixes the bug. :)
 *
 * Author: Jarkko Linnanvirta / IT-Palvelu Taitava (GitHub @Taitava)
 */
class BlogPostLanguageFix extends DataExtension
{
	public function onBeforeWrite()
	{
		parent::onBeforeWrite();
		$locale = Translatable::get_current_locale();
		if ($this->owner->Locale !== $locale) $this->owner->Locale = $locale;
	}
}
```

Add to mysite/_config/config.yml:
```
BlogPost:
  extensions:
    - BlogPostLanguageFix
```

Please note that this does not solve the original bug, but rather fixes the symptom in a quick and dirty way. I have done very little testing after creating this extension. I created new BlogPosts in Finnish and in English and checked in the database that the locales are now saved correctly. I found no errors. If you use this fix, can you please report back here if it worked for you, and also of course if it didn't? Tell me also what locales you are using. Thank you!  :)

**Comment by riddler7** [comment]
Ran into the same problem, looks to be a little more extensive. Happens whenever I try to add a new page (e.g. with the "New page" button above the site tree).

Looks like the issue is Translatable sets the default for Locale to the default locale (likely english). The onBeforeWrite only sets the Locale to the current locale if Locale isn't already set (which it was by the default value).

**Comment by Taitava** [comment]
Sounds reasonable. @silverstripe-issues , is this information enough for inspecting the issue? If still needed, I think I can write some example code showing the bug.

**Comment by dhensby** [comment]
I'm not sure who @silverstripe-issues is (@chillu?), @Taitava and you supply some code just for clarity's sake? thanks

**Comment by Taitava** [comment]
Yes, just for clarity if needed :).

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
