### ISSUE TITLE
Version chaos that nobody is waiting for

### ISSUE THREAD

**Issue by yurigoul** [silverstripe/silverstripe-translatable#227]
I have the problem described here:

https://github.com/silverstripe/silverstripe-translatable/issues/168

According to this link my problems can be solved downloading master 2.0 - but where? There is no download link.....

I downloade the most recent stable version of silverstripe = plus translatable from the addons section - get error after error - and then in the above link there is .... what solution solution exactly?

The official silverstripe link to translatable for silverstripe version 3.2 links to a page on github here https://github.com/silverstripe/silverstripe-translatable/issues/168. That page links to 404 errors with almost every external file and it says for this version version 4x of silverstripe is needed.

So where then is the version for version 3.2?

Please be consistent, please create links that work. This is not the first time I am totally at loss with silverstripe and it is a waste of my time. Every time I have to find at least 10 sources to make something work.

**Comment by tractorcow** [comment]
Hi @yurigoul ,

The most effective way to manage silverstripe module dependencies is with [composer](https://getcomposer.org/). I invite you to try it out and see if it helps improve your module management.

When we are discussing version dependencies, these are typically the version set in a projects composer.json file, which determines the numeric (or branch) versions of each module.

> That page links to 404 errors with almost every external file and it says for this version version 4x of silverstripe is needed.

That link doesn't say to use 4.x, it says to use translatable 2.0, which is designed for silverstripe 3.1, as per https://github.com/silverstripe/silverstripe-translatable/blob/2.0/composer.json

Note that #168 is nearly two years old. Since then we've released silverstripe 3.2, which has a new translatable branch 2.1. If you are using composer to manage your dependencies it should point this out to you when trying to install. See https://github.com/silverstripe/silverstripe-translatable/blob/2.1/composer.json to example the dependencies for this version (note that `~3.2' means it also supports 3.3).

Setup this in your project and do `composer update` in your project to get a working site setup. Feel free to customise to your projects needs.

```json
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"silverstripe/cms": "3.2.x-dev",
		"silverstripe/framework": "3.2.x-dev",
		"silverstripe/reports": "3.2.x-dev",
		"silverstripe/siteconfig": "3.2.x-dev",
		"silverstripe-themes/simple": "3.1.*",
		"silverstripe/translatable": "2.1.x-dev"
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}
```

If you need more information, we have a "getting started" guide on the docs to help users get up and running with composer and managing silverstripe modules.

https://docs.silverstripe.org/en/3.2/getting_started/composer/

Happy coding; I hope that solves your issues. ;)

**Comment by camfindlay** [comment]
Thanks @tractorcow. Also @yurigoul there is a video and written information about the concept of managing modules and other addon dependancies with composer for SilverStripe over at http://www.silverstripe.org/learn/lessons/dependencies-and-modules worth a watch.

**Comment by yurigoul** [comment]
The page that your github for translatable opens with has the 404 external
links - as I said: it is always the same problem with silverstripe
information.

**Comment by tractorcow** [comment]
@yurigoul please show us what link you are talking about? Are you talking about a link on addons.silverstripe.org, or elsewhere?

**Comment by yurigoul** [comment]
https://github.com/silverstripe/silverstripe-translatable

Requirements
> SilverStripe Framework 4.x (master) and CMS 4.x (master)


Plus one 404 error link

https://github.com/silverstripe/silverstripe-translatable/blob/master/docs/en/index.md

8 x 404 error on about 15 links - 3 of those go to alternatives to
translatable, 2 go to W3C - so that leaves two working links on the inner
workings of this plugin.

**Comment by tractorcow** [comment]
That makes a lot more sense, thanks!

The home page of translatable is on the master branch; If you checkout https://github.com/silverstripe/silverstripe-translatable/tree/2.1 home page you'll see the version dependencies are for 3.2.

I've changed the default branch to 2.1 now so that no one else will be confused.

I'll create a separate issue to track and fix the broken documentation links. @camfindlay can you please check the documentation and help with this?

**Comment by yurigoul** [comment]
The 404 errors shows clearly how old this information is - you are even
missing information on how the yaml files need to be structured - you are
not even mentioning them there.

Nor is that information mentioned in the index.md for the 2.1 version of
the link:

https://github.com/silverstripe/silverstripe-translatable/blob/2.1/docs/en/index.md

File has the same 404 errors.

**Comment by tractorcow** [comment]
Thanks for the issue report, @yurigoul 

We'll take care of the documentation issues. You are quite right, those docs haven't been maintained well, but we'll sort that out.

I've created https://github.com/silverstripe/silverstripe-translatable/issues/228 to track documentation issues that need resolving.

In the mean time, let me know if you need any more help setting up your project. Was the example composer usage helpful for your use case?

**Comment by yurigoul** [comment]
I already found the 2.1 version - I do not understand why the master is not
the most recent version - but maybe the is just me.

The only thing I am still looking for is the fastest way to translate the
old php format to the yaml format....

**Comment by tractorcow** [comment]
Mostly because master is for a yet-unreleased version, so it's not quite ready for use yet.

Note that silverstripe-translatable has nothing to do with the framework i18n translation feature; This is a module for creating translated dataobjects in the CMS.

If you are looking for reference on the yml translations you need to check the core documentation at https://docs.silverstripe.org/en/3.2/developer_guides/i18n/

There is a project that was used to convert the old PHP translations at https://github.com/chillu/i18n_yml_converter, but I can't vouch for whether it still works after four years.

**Comment by yurigoul** [comment]
Thanks for the links

Regarding the issue with the Master: the github link is where you send the
general public to when they want to download a plugin to enhance their
silverstripe install. Some people might be a bit confused by this, since
most people probably want to install a cms and that is that. Given the
other topic, I was not the only one who was confused.

**Comment by tractorcow** [comment]
Yep, that's why I've changed the default branch to 1.1. It's a lot more appropriate for new users.
