### ISSUE TITLE
Holder: SS4 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-translatable#263]
Just logging to hold issues related to SS4 compatibility.

## Required

* Namespaces
* API updates: config, versioned, DB/schema managers
* Update tests

I've made a start in my fork's `feature/ss4-compat` branch - will continue to work at it.

**Comment by thezenmonkey** [comment]
I tried adding the Translatable module to a clean SS4beta6; currrently TranslatableCMSMainExtension extends Extension class which no longer exists

**Comment by robbieaverill** [comment]
Hey @thezenmonkey - the [`Extension` class](https://github.com/silverstripe/silverstripe-framework/blob/master/src/Core/Extension.php) definitely still exists, but it has been namespaced and moved to a different file location than SS3

**Comment by Martimiz** [comment]
Hi Robbie, 

Is your feature/ss4-compat branch actually the one that will be merged into master later? I'm asking because I'll need to upgrade the LanguagePrefix module, that uses/extends Translatable. So I'll be needing a working version that at least resembles the final Translatable for 4.0...

Thanks, Martine

**Comment by robbieaverill** [comment]
@Martimiz it might be yeah, but I wouldn't base anything from it now - it's not ready

**Comment by JorisDebonnet** [comment]
With SilverStripe 4.0.0-beta1 now available, any chance this could be expedited? I was considering to try the upgrader tool on this module myself, but if there's more to it than that, I unfortunately won't be able to spend enough time on it soon...

**Comment by Martimiz** [comment]
+1
If I can help, please give some clues as to what needs still to be done :)

**Comment by robbieaverill** [comment]
Since the API is more stable now it's a better time to look at this again

**Comment by robbieaverill** [comment]
Ok, I'm starting to make some progress with this - the latest round of builds are failing but at least most of the tests are passing: https://travis-ci.org/robbieaverill/silverstripe-translatable/jobs/250241104

**Comment by Martimiz** [comment]
1) SilverStripe\Translatable\Tests\TranslatableTest::testGetTranslationByStage
    InvalidArgumentException: Invalid stage name ""

Problem: Versioned::get_stage() is not set at this point. This is solved by setting the stage to 'Stage' first:

    public function testGetTranslationByStage()
    {
        Versioned::set_stage('Stage');
        $publishedPage = new SiteTree();
        ...

I think this is correct, as stage would be 'Stage in the CMS as well. 'Live' will not work, because write() would then change the title in the Stage ánd Live version of the page. But maybe this setting should live in the setup()?

What do you think?

**Comment by robbieaverill** [comment]
Yes I agree @martimiz however I feel like it should be draft by default anyway. I'll do some hunting.

**Comment by Martimiz** [comment]
Agree - since set_stage() doesn't accept an empty stage, it should also never initially be that! A Framewook thingy...

**Comment by Martimiz** [comment]
Next:

    public function testLocaleGetParamRedirectsToTranslation()
    {  
        ...
        $response = $this->get(Controller::join_links($origPage->URLSegment, '?locale=de_DE'));
        $this->assertEquals(301, $response->getStatusCode(), 'Locale GET param causes redirect if it exists');

resulting in:

    1) SilverStripe\Translatable\Tests\TranslatableTest::testLocaleGetParamRedirectsToTranslation
    Locale GET param causes redirect if it exists
    Failed asserting that 200 matches expected 301.

This seems to be because $origPage->URLSegment . '?locale=de_DE' doesn't redirect to the German translation, but returns a 404 instead. If I try this in ss3 2.3.6/translatable 2.2.*@dev (cms) I get the same result, could it be this hasn't been working for a while? 

If it actually doesn't work in ss3 - would it need to work in ss4 (multiple urls to the same content and all)?

**Comment by robbieaverill** [comment]
Interesting - it should work, since this test exists in the SS3 release line and is passing

**Comment by Martimiz** [comment]
Hi,

* TranslatableTest::testLocaleGetParamRedirectsToTranslation (3)
* TranslatableTest::testRootUrlDefaultsToTranslatedLink (5)

These failures relate to namespacing and the fact that SilverStripe and Translatable are coupled: once it's sure the current Translatable namespacing will be accepted, the following changes should be performed on SilverStripe:

- if (class_exists('Translatable')  --> if (class_exists(Translatable::class)
- use Translatable --> use SilverStripe\Translatable\Model\Translatable;
- has_extension('Translatable') --> has_extension(Translatable::class)
- hasExtension('Translatable') --> hasExtension(Translatable::class)

Martine

**Comment by Martimiz** [comment]
* TranslatableTest::testChangingClassOfDefaultLocaleTranslationChangesOthersWhenPublished

Hi,
SiteTree::doPublish() is moved to Versioned::doPublish() and deprecated in favor of Versioned::publishRecursive(). It needs a write() prior to publishing for this test to work...

I think, because these are simple pages, copyVersionToStage() would do as well, but also needs the write():

    TranslatableTest #331:  $enST->doPublish() --> $enST->publishRecursive();
    TranslatableTest #343:  $enST->doPublish() --> $enST->write(); 
                                                   $enST->publishRecursive();

If you agree, I'll send you a pull request

**Comment by Martimiz** [comment]
Hi, 

* TranslatableSearchFormTest::testPublishedPagesMatchedByTitleInDefaultLanguage (1)

This is a double issue: 

(1) the SilverStripe SearchEngine will always search on 'SiteTree' (bug) while Translatable adds SiteTree_Live.Locale to the query (correct). This gives an error. See pull request: https://github.com/silverstripe/silverstripe-framework/pull/7171/commits/f38d8c98193a711f6a462116f4a080e867f050a0

(2) SearchForm::getResults() no longer accepts parameters, but wants to read them from URL, as in:

    $request->requestVar('searchlocale');

So unless there is a way to add params to the request (is there?) It may be the test needs to use the url, and retreive the values from the respons somehow... What do you think?

Martine

**Comment by robbieaverill** [comment]
Wow, thanks for the thorough investigation! Yes, feel free to make a PR into my fork branch, then once the tests are almost all passing we can PR all of t back here

**Comment by Martimiz** [comment]
A problem with this process has come up:   as to the updates to SS4, I forgot to mention this one:

* use Translatable;   --> use SilverStripe\Translatable\Model\Translatable;

Until this has been merged into SS, the Translatable tests will keep failing... But I guess SS will only accept a pull for the official Translatable branche..???? :(

**Comment by robbieaverill** [comment]
Hey @Martimiz - thanks for all your investigation.

I've applied all your suggestions very quickly (incuding your framework patch) - you've fixed most of the failures!

As for pull requests, my intention is to open one once the build is pretty much clean and we've established what to do with the core module coupling with translatable in the short to medium term (obviously the goal would be to decouple it - cc @dhensby - what do you think?).

@Martimiz feel free to pull request changes into my fork, it will get pull requested back into the main repository at some point and I'd love for your work to be credited in that!

**Comment by Martimiz** [comment]
Thanks @robbieaverill, 
Glad to be of help :) Pull request done: https://github.com/robbieaverill/silverstripe-translatable/pull/1

**Comment by Martimiz** [comment]
Looking at extensions.yml:

1. In my setup TranslatableCMSMainExtension isn't loading. Can you confirm (missing languageselect over sitetree in cms)? In that case I have a pull for that.

2. What does ModelController stand for? My guess was ModalController, but for now I can't get it to load TranslatableEditorToolbarExtension

3. Can you confirm Translatable is loading for DataQuery? it is a base class and I'm not sure they're actually extendable like that...

**Comment by Martimiz** [comment]
As to TranslatableSiteConfigTest:

This last one is a serious bug, not just a test issue...

On the actual website SiteConfig::make_site_config() keeps creating records for the default locale every time a page in a different language is requested  - until the proper SiteConfig is added manually via the CMS|Settings. 

Haven't been able to track that one down yet :( might need your help for that...

**Comment by Martimiz** [comment]
OK, found the SiteConfig issue and added it to this pull:  https://github.com/robbieaverill/silverstripe-translatable/pull/2. Tests don't fail anymore on my site of things.

I'll add a fix for TranslatableCMSMainExtension not loading onto LeftAndMain as soon as you confirm this is an issue, not just a glitch on my system. Because I actually have no idea why it shouldn't work in my current setup, unless it is due to some change in config behaviour..?

**Comment by robbieaverill** [comment]
WIP pull request open to show progress at #264

**Comment by stefanhuber** [comment]
Can I start a ss4 project now with translatable in place? I have to start a new multilingual project, but I am not sure if I can use ss4 already?

**Comment by robbieaverill** [comment]
@stefanhuber no sorry, it's not quite ready. I'd expect it will be done in te next month or two though. Alternatively you could check out tractorcow/silverstripe-fluent which has some promising SS4 support underway.

**Comment by stefanhuber** [comment]
@robbieaverill thx for your prompt reply!

**Comment by Martimiz** [comment]
Hi Robbie,
Any news on this? Any steps taken on preparing the CMS for the Translatable namespacing?

I was wondering if it would be safe to update my LanguagePrefix module based on the curren state of your fork, because that might take a bit of work as well...

Martine

**Comment by robbieaverill** [comment]
@Martimiz SS Ltd isn't focussing on Translatable at the moment. It will probably happen again soon though. We're likely to be shifting to a new version of Fluent as the preferred translation module, which will encompass a combination of Translatable and Fluent features for SS4.

>I was wondering if it would be safe to update my LanguagePrefix module based on the curren state of your fork, because that might take a bit of work as well...

You're welcome to keep contributing and using it, but I probably wouldn't recommend it at this point

**Comment by Martimiz** [comment]
@robbieaverill 
Ok, noted. I always thought Translatable a bit of a dinosaur, the fact that I had to create that prefix module at all. Still it had a couple of features Fluent didn't have, so... 

I hope there will be some way to 'translate' Translatable site to Fluent at some point, because now it's probably keeping a lot of people from upgrading or designing...

Pitty all that work though :)

**Comment by robbieaverill** [comment]
Your work probably won't be wasted! It'll live on in some way or another. Yes we will have a translatable to fluent migration tool or guide or both.

**Comment by Martimiz** [comment]
:)) sounds somewhat mystical, but hey, let's keep cherishing the romance in programming...

Thanks

**Comment by maxime-rainville** [comment]
We're not looking at doing a SS4 version of translatable. Use fluent instead.
