### ISSUE TITLE
[User Error] Uncaught InvalidArgumentException: Invalid locale "ra_HF"

### ISSUE THREAD

**Issue by bumbus** [silverstripe/silverstripe-translatable#268]
Is there a way to catch this error? Wouldn't it be more user-friendly if this function falls back to default locale instead of crashing?

```
316 	 * Set the reading language, either namespaced to 'site' (website content)
317 	 * or 'cms' (management backend). This value is used in {@link augmentSQL()}
318 	 * to "auto-filter" all SELECT queries by this language.
319 	 * See {@link disable_locale_filter()} on how to override this behaviour temporarily.
320 	 * 
321 	 * @param string $lang New reading language.
322 	 */
323 	static function set_current_locale($locale) {
324 		if($locale && !i18n::validate_locale($locale)) {
325 			throw new InvalidArgumentException(sprintf('Invalid locale "%s"', $locale));
326 		}
327 		
328 		self::$current_locale = $locale;
329 	}	
330 	
331 	/**

```

**Comment by NightJar** [comment]
The exception is thrown to warn a developer that something undefined has been referenced. To my knowledge there is no way for a user to cause this error, and should a module developer allow it then the way to catch the error is to:

```php
try {
    i18n::set_current_locale($locale);
} catch (InvalidArgumentException $e)
    // Do something, maybe? Maybe not.
}
```

As per http://php.net/manual/en/language.exceptions.php

If this error is not used by user input, and you wish to define a locale that is otherwise invalid, then you can edit the `i18n.all_locales` configuration setting to add one, as this is what is checked against to generate the error: https://github.com/silverstripe/silverstripe-framework/blob/3.6/i18n/i18n.php#L2472
(and the same logic exists throughout this module, e.g.: https://github.com/silverstripe/silverstripe-translatable/blob/2.2/code/model/Translatable.php#L325 )

I think the current behaviour is both correct and desirable.

**Comment by bumbus** [comment]
Hi @robbieaverill,
thanks for your reply. The point is that no one has control over what is passed as url variable to locale (e.g. http://somewhat.com/?locale=some_invalid_locale_value). If a invalid locale param is passed you will receive a 500 error.

I just ask myself, why this function does not check against Translatable:: $allowed_locales and if it is not present, why not fall back to default locale instead of bailing?

**Comment by robbieaverill** [comment]
Oh! Ok that's more helpful. I'll reopen as a bug.

**Comment by robbieaverill** [comment]
I don't think falling back to a default locale would be desirable behaviour. What about if we return a 404 instead?

**Comment by ScopeyNZ** [comment]
404 makes semantic sense. :shipit:

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
